-- Execute no SQL Editor do Supabase.

create table if not exists public.questions_catalog (
  id bigint generated by default as identity primary key,
  source_uid text not null unique,
  organization text not null,
  contest text not null,
  bank text not null,
  cargo text,
  year integer,
  subject text not null,
  topic text,
  subtopic text,
  difficulty text not null default 'Média',
  statement text not null,
  options jsonb not null,
  answer text not null check (answer in ('A','B','C','D','E')),
  explanation text,
  tags jsonb not null default '[]'::jsonb,
  source_url text not null,
  source_kind text not null,
  license_name text,
  status text not null default 'published',
  confidence numeric(4,3) not null default 0.9,
  official_number integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.source_documents (
  id bigint generated by default as identity primary key,
  source_id text not null,
  title text not null,
  url text not null,
  document_kind text not null,
  content_hash text not null unique,
  content_type text,
  extraction_confidence numeric(4,3),
  text_length integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  discovered_at timestamptz not null default now()
);

create table if not exists public.collector_runs (
  id bigint generated by default as identity primary key,
  source_id text not null,
  status text not null,
  documents_found integer not null default 0,
  questions_published integer not null default 0,
  message text,
  created_at timestamptz not null default now()
);

alter table public.questions_catalog enable row level security;
alter table public.source_documents enable row level security;
alter table public.collector_runs enable row level security;

drop policy if exists "Public read published questions" on public.questions_catalog;
create policy "Public read published questions"
on public.questions_catalog for select
to anon
using (status = 'published');

create index if not exists idx_questions_catalog_status on public.questions_catalog(status);
create index if not exists idx_questions_catalog_subject on public.questions_catalog(subject);
create index if not exists idx_questions_catalog_contest on public.questions_catalog(contest);
create index if not exists idx_source_documents_source on public.source_documents(source_id, discovered_at desc);
create index if not exists idx_collector_runs_source on public.collector_runs(source_id, created_at desc);
